### ISSUE TITLE
Wireframes & ERD

### ISSUE THREAD

**Issue by tilleraj** [nss-evening-cohort-9/nutshell-peanut#10]

**Comment by tilleraj** [comment]
## Dashboard
![Peanuts00](https://user-images.githubusercontent.com/701829/58924481-9bcefd80-8709-11e9-9664-ea2b9eb6d185.PNG)

**Comment by tilleraj** [comment]
## Diary
![Peanuts01](https://user-images.githubusercontent.com/701829/58924512-b5704500-8709-11e9-8b77-6f7678defb33.PNG)

**Comment by tilleraj** [comment]
## News Articles
![Peanuts02](https://user-images.githubusercontent.com/701829/58924525-c9b44200-8709-11e9-9ee3-4254b402fd89.PNG)

**Comment by tilleraj** [comment]
## Calendar
![Peanuts03](https://user-images.githubusercontent.com/701829/58924534-d6389a80-8709-11e9-989a-b9351a7f8574.PNG)

**Comment by tilleraj** [comment]
## Messages
![Peanuts04](https://user-images.githubusercontent.com/701829/58924549-e2bcf300-8709-11e9-9a78-ffb2d0c6bf5f.PNG)

**Comment by tilleraj** [comment]
## ERD
<img width="635" alt="Screen Shot 2019-06-04 at 7 58 54 PM" src="https://user-images.githubusercontent.com/701829/58924656-5b23b400-870a-11e9-9210-630725043948.png">

**Comment by GregStephen** [comment]
<img width="637" alt="Screen Shot 2019-06-04 at 9 07 23 PM" src="https://user-images.githubusercontent.com/35859167/58925436-1fd6b480-870d-11e9-83c2-4f38a835fd6c.png">
